config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  f_aliases:
    dst: ~/.aliases
    src: aliases.sh
  f_zshrc:
    dst: ~/.zshrc
    src: zshrc.sh
profiles:
  home:
    dotfiles:
    include:
      - skip
  skip:
    dotfiles:
    - f_aliases
    - f_zshrc
