actions:
  git-completion-bash: cp extras/git-completion.sh ~/.git-completion.sh && cp extras/git-prompt.sh ~/.git-prompt.sh
trans:
  disclaimer: python scripts/disclaimer.py {0} > {1}

config:
  backup: true
  create: false
  dotpath: ./dotfiles
dotfiles:
############ ZSH #############
  f_zshrc:
    dst: ~/.zshrc
    src: zshrc.sh
    trans: disclaimer

############ BASH #############
  f_bashrc:
    dst: ~/.bashrc
    src: bashrc.sh
    actions:
      - git-completion-bash
  f_bash_ps1:
    dst: ~/.bash-ps1.bash
    src: bash-ps1.sh
    trans: disclaimer

############ OTHER #############
  f_profile:
    dst: ~/.base_profile
    src: profile.sh
    link: false
    trans: disclaimer
  f_aliases:
    dst: ~/.aliases
    src: aliases.sh
    trans: disclaimer

profiles:
  bash:
    dotfiles:
      - f_bashrc
      - f_bash_ps1
      - f_aliases
      - f_profile
  zsh:
    dotfiles:
      - f_zshrc
      - f_aliases
      - f_profile
  home:
    include:
      - bash
  skip:
    include:
      - zsh
